backend:
  name: github
  repo: DonJosue3/aqe
  branch: main
  base_url: https://aqe-oauth.ishakaryayodonjosue.workers.dev
  auth_endpoint: auth

media_folder: "public/images/products"
public_folder: "/images/products"

collections: []